### ISSUE TITLE
feat: customize and delete scaffoldeth boilerplate components like footer

### ISSUE THREAD

**Issue by Markkos89** [zenbitETH/AttestDeFi#6]
## - header to be customized
![image](https://github.com/user-attachments/assets/b3b200c1-f8f0-45d4-a6f9-25abc97a607a)

## - remove footer or customize it 
![image](https://github.com/user-attachments/assets/de484e01-7e09-40be-87fe-ed75297b5f8e)

**Comment by HabacucMX** [comment]
closed #11
